# Neon Database Configuration
# Replace these with your actual credentials
NEON_DB_HOST = "your-neon-host-here"
NEON_DB_NAME = "your-database-name"
NEON_DB_USER = "your-username"
NEON_PASSWORDLESS_TOKEN = "your-token-here"
NEON_SSLMODE = "require"
