# Neon Database Configuration
NEON_DB_HOST = "ep-summer-hall-ad52e1og-pooler.c-2.us-east-1.aws.neon.tech"
NEON_DB_NAME = "neondb"
NEON_DB_USER = "neondb_owner"
NEON_PASSWORDLESS_TOKEN = "npg_0HfEmGgOYVp3"
NEON_SSLMODE = "require"
